
import __ASTRO_IMAGE_IMPORT_Z18zpfg from "../../assets/images/msf1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2025-12-24-msf.md";
import __ASTRO_IMAGE_IMPORT_ZYTcD1 from "../../assets/images/msf2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2025-12-24-msf.md";
import __ASTRO_IMAGE_IMPORT_ZQe01L from "../../assets/images/msf3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2025-12-24-msf.md";
import __ASTRO_IMAGE_IMPORT_UFBSI from "../../assets/images/cornfield-screenshot-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md";
import __ASTRO_IMAGE_IMPORT_Z2ckzXh from "../../assets/images/cornfield-screenshot-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md";
import __ASTRO_IMAGE_IMPORT_1H1gUA from "../../assets/images/cornfield-screenshot-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md";
import __ASTRO_IMAGE_IMPORT_Z17TDhC from "../../assets/images/cornfield-coordinates.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md";
import __ASTRO_IMAGE_IMPORT_Zf9E1l from "../../assets/images/cornfield-screenshot-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md";
import __ASTRO_IMAGE_IMPORT_2dqtnB from "../../assets/images/picoweb1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-24-picoctf-crack-the-gate-1.md";
import __ASTRO_IMAGE_IMPORT_Z1w5NdF from "../../assets/images/picoweb2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-24-picoctf-crack-the-gate-1.md";
import __ASTRO_IMAGE_IMPORT_ZOHdln from "../../assets/images/wireshark-ss.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-30-brainhack-2023-eazy-network-analysis.md";
import __ASTRO_IMAGE_IMPORT_Z1rJMR7 from "../../assets/images/wireshark2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-30-brainhack-2023-eazy-network-analysis.md";
import __ASTRO_IMAGE_IMPORT_uaruE from "../../assets/images/kraken-diagram.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2026-05-21-cddc-2026-kraken.md";
export default new Map([["../../assets/images/msf1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2025-12-24-msf.md", __ASTRO_IMAGE_IMPORT_Z18zpfg], ["../../assets/images/msf2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2025-12-24-msf.md", __ASTRO_IMAGE_IMPORT_ZYTcD1], ["../../assets/images/msf3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2025-12-24-msf.md", __ASTRO_IMAGE_IMPORT_ZQe01L], ["../../assets/images/cornfield-screenshot-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md", __ASTRO_IMAGE_IMPORT_UFBSI], ["../../assets/images/cornfield-screenshot-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md", __ASTRO_IMAGE_IMPORT_Z2ckzXh], ["../../assets/images/cornfield-screenshot-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md", __ASTRO_IMAGE_IMPORT_1H1gUA], ["../../assets/images/cornfield-coordinates.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md", __ASTRO_IMAGE_IMPORT_Z17TDhC], ["../../assets/images/cornfield-screenshot-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-13-cornfield.md", __ASTRO_IMAGE_IMPORT_Zf9E1l], ["../../assets/images/picoweb1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-24-picoctf-crack-the-gate-1.md", __ASTRO_IMAGE_IMPORT_2dqtnB], ["../../assets/images/picoweb2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-24-picoctf-crack-the-gate-1.md", __ASTRO_IMAGE_IMPORT_Z1w5NdF], ["../../assets/images/wireshark-ss.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-30-brainhack-2023-eazy-network-analysis.md", __ASTRO_IMAGE_IMPORT_ZOHdln], ["../../assets/images/wireshark2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2025-12-30-brainhack-2023-eazy-network-analysis.md", __ASTRO_IMAGE_IMPORT_Z1rJMR7], ["../../assets/images/kraken-diagram.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwriteups%2F2026-05-21-cddc-2026-kraken.md", __ASTRO_IMAGE_IMPORT_uaruE]]);
		